### ISSUE TITLE
hashid

### ISSUE THREAD

**Issue by pjebs** [jenssegers/optimus#1]
Is this quicker than hashid (using an all-number alphabet)?

http://hashids.org/

**Comment by pjebs** [comment]
Also it is called Knuth's integer hash (not Kunth)

**Comment by jenssegers** [comment]
Wow, what a typo!

I don't think this method will be any slower than hashids. If you take a look at the Optimus class you wil see that the technique is super simple. I will do a benchmark soon, but performance won't be an issue ;)

**Comment by jenssegers** [comment]
These are the results for a simple benchmark that simply constructs both classes and then encodes and decodes an id for 100.000 times:

- Optimus: 445ms
- Hashids: 32.271s

**Comment by pjebs** [comment]
Converted your code to go: https://github.com/pjebs/optimus-go

**Comment by pjebs** [comment]
http://hashids.org/#alternatives

**Comment by pjebs** [comment]
Expect more traffic

**Comment by jenssegers** [comment]
Cool!
