### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by Propaganistas** [jenssegers/optimus#10]
Hi

Upon executing the `spark` command, I get the following error:

    Segmentation fault: 11

Debugging reveals that the problem resides in the BigInteger calls to phpseclib...

Any ideas on this? I'm on Mac OS X 10.10.

**Comment by jenssegers** [comment]
That's weird. Is there a stack trace?

**Comment by Propaganistas** [comment]
Yeah sure. Please take a look at the following pastebin:

http://pastebin.com/tb7XThYY
