### ISSUE TITLE
Inconsistent encoding/decoding

### ISSUE THREAD

**Issue by jeteon** [jenssegers/optimus#12]
I'm not sure whether I'm doing something wrong, but in an initial test of the code using the numbers in the  readme, the mappings I get are:

```
0       =>1163945558    =>0
1       =>458047115     =>0
2       =>2033899500    =>0
3       =>1609067713    =>4
4       =>1037370658    =>0
5       =>327342599     =>0
6       =>1886417784    =>8
7       =>1448937565    =>8
8       =>873111742     =>0
9       =>184056211     =>16
```

The code that I'm using to generate this simply encodes the integer and then decodes it again:

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Jenssegers\Optimus\Optimus;

$optimus = new Optimus(1580030173, 59260789, 1163945558);

for($i = 0; $i < 10; $i++)
{
        $enc = $optimus->encode($i);
        echo $i . "\t=> " . $enc . "\t=> " . $optimus->decode($enc) . "\n";
}
```

I then used `spark` to generate a different triplet of parameters corresponding to `new Optimus(297501427, 217343547, 139284431)` and got:

```
0       => 139284431    => 0
1       => 435604796    => 0
2       => 725240361    => 0
3       => 1031784214   => 0
4       => 1319322627   => 0
5       => 1357169008   => 0
6       => 1646812797   => 0
7       => 1953356650   => 0
8       => 93411415     => 8
9       => 400217412    => 16
```

Also, for me, both the README and `spark` generated parameters fail the test on the README and give `(PRIME * INVERSE) & MAXID = 0`. Is there perhaps a step I have missed or a particular PHP plugin I need to have active for it to work?

**Comment by jenssegers** [comment]
I ran your example and got:

```
0	=> 1163945558	=> 0
1	=> 458047115	=> 1
2	=> 2033899500	=> 2
3	=> 1609067713	=> 3
4	=> 1037370658	=> 4
5	=> 327342599	=> 5
6	=> 1886417784	=> 6
7	=> 1448937565	=> 7
8	=> 873111742	=> 8
9	=> 184056211	=> 9
```

What is your environment?

**Comment by jeteon** [comment]
I suspect that its an issue with my setup differing from yours but can't say where. I'm running 32 bit Kubuntu 14.04 on Kernel 3.13.0-63-generic. PHP is version 5.5.9-1ubuntu4.11 with Zend Engine v2.5.0.

**Comment by jeteon** [comment]
Are you running a 64 bit machine, by any chance?

**Comment by jeteon** [comment]
The mapping forward seems to be consistent. And if I try the numbers in Python it works out. Its definitely the backward mapping that's the issue. On Python, it seems to require a long so it must be overflowing with PHP native integers.

**Comment by jenssegers** [comment]
Must be related to 32 bit then I think. Will spin up a 32 bit VM and check it out.

**Comment by iotch** [comment]
I'm getting the same results as OP with the example from documentation:

````
0       =>1163945558    =>0
1       =>458047115     =>0
2       =>2033899500    =>0
3       =>1609067713    =>4
4       =>1037370658    =>0
5       =>327342599     =>0
6       =>1886417784    =>8
7       =>1448937565    =>8
8       =>873111742     =>0
9       =>184056211     =>16
````
Running php7 rc6 on 32 bit CentOS6.

**Comment by jenssegers** [comment]
Seems to be an issue related to 32 bit.

**Comment by iotch** [comment]
Yep, it works on 32bit with the GMP (sorry for php7 code, it's just for demonstration):

````php
    /**
    * Encode an integer.
    *
    * @param int $value
    * @return int
    */
    public function encode(int $value)
    {
        return (int) gmp_mul($value, $this->prime) & static::MAX_INT ^ $this->xor;
    }
    
    /**
    * Decode an integer.
    *
    * @param int $value
    * @return int
    */
    public function decode(int $value)
    {
        return (int) gmp_mul($value ^ $this->xor, $this->inverse) & static::MAX_INT;
    }
````

**Comment by jenssegers** [comment]
Mh that is interesting. A possible fix would be for 32bit users to require the GMP extension and use `gmp_mul` if it is available.

**Comment by jenssegers** [comment]
Can you guys clone the master brach and run the tests? 32 bit systems should now use the `gmp` extension.

**Comment by jenssegers** [comment]
Just booted a 32bit VM and it looks like it is working correctly :)

**Comment by iotch** [comment]
Same here, thanks!
