### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by KwadroNaut** [jenssegers/optimus#14]
You explain very well on how to use it, but not what it actually does/how it gets done what it does. It's all relatively small, so I (think I) figured it out by glancing at the source, still would be nice if you could expand.
- const MAX_INT = 2147483647; Does that include this Mersenne prime or one less?
- why chmod 755? Everyone should be able to execute/recalculate the ids?

**Comment by henryejemuta** [comment]
> You explain very well on how to use it, but not what it actually does/how it gets done what it does. It's all relatively small, so I (think I) figured it out by glancing at the source, still would be nice if you could expand.
> 
> * const MAX_INT = 2147483647; Does that include this Mersenne prime or one less?
> * why chmod 755? Everyone should be able to execute/recalculate the ids?

Just runing `php vendor/bin/optimus spark` would generate the required numbers for you to work with

**Comment by jenssegers** [comment]
Also see https://github.com/jenssegers/optimus/issues/35
