### ISSUE TITLE
Silex integration documentation

### ISSUE THREAD

**Issue by amustill** [jenssegers/optimus#22]
Firstly, great library and thanks for your work.

My development studio released a Silex integration last week and thought it may help some people if this was included within the documentation. I'm more than happy to create a PR for the `README.md` if required?

https://github.com/letsjaam/silex-optimus-provider

Many thanks.

**Comment by jenssegers** [comment]
Sure, you can add a section about framework integrations :)

**Comment by amustill** [comment]
Done and thanks!
