### ISSUE TITLE
Information on collisions

### ISSUE THREAD

**Issue by rauanmaemirov** [jenssegers/optimus#3]
Hey, Jens.
I'd like to know if collisions are possible in optimus.

Some info in README would be nice.

**Comment by jenssegers** [comment]
I recently did a quick test and was unable to find collisions. There is probably some mathematical proof of this somewhere :p

**Comment by jenssegers** [comment]
Just did a test for every positive integer going from 0 to Optimus::MAX_INT (2147483647) and can confirm that there are no collisions.
