### ISSUE TITLE
Laravel 7.0 incompatibilities

### ISSUE THREAD

**Issue by Garanaw** [jenssegers/optimus#48]
The last released Laravel has updated his internal dependencies based on Symfony to the 5.* series, including the console.

As for this library, it still requires the 3.0 && 4.0 series, preventing to upgrade the framework.

For what I could see in the library, the only exception is the `InvalidPrimeException`, which extends from `RangeException`, which extends from `RuntimeException`, which extends from `Exception`, which at last implements the `Throwable` interface. Being that the only requirement (AFAIK), this can be satisfiable by just adding `|^5.0` to the `composer.json` file under the `symfony/console` dependency.

Happy to PR it if you're busy

**Comment by jenssegers** [comment]
A PR would be lovely!

**Comment by jenssegers** [comment]
Should be fixed with https://github.com/jenssegers/optimus/pull/47
