### ISSUE TITLE
support for phpseclib v3?

### ISSUE THREAD

**Issue by wivaku** [jenssegers/optimus#53]
Depedency is now [phpseclib v2](https://github.com/jenssegers/optimus/blob/559241280cd8ed96006f496f89df4442bd6d7857/composer.json#L15):

Is it possible to support [phpseclib v3](https://github.com/phpseclib/phpseclib/releases) which was released recently?

**Comment by tonilxm** [comment]
Please make this happen since laravel passport 10.x already using phpseclib3. this will make out life much easier.
