### ISSUE TITLE
Laravel 5.1 problem

### ISSUE THREAD

**Issue by marty12321** [jenssegers/optimus#7]
Hi,
I'd like to use it in Laravel but all the time have a problem with namespace, 
if I add it in the controller
use Jenssegers\Optimus;
get error 'Class 'jenssegers\optimus' not found'
but in vendor folder it is present with all files
I did comopser dump-autoload
 it is the only package, I have problem with

**Comment by jenssegers** [comment]
Use `Jenssegers\Optimus\Optimus`. Updated readme as well.
