### ISSUE TITLE
What's the maximum value optimus can handle?

### ISSUE THREAD

**Issue by shpeilin** [jenssegers/optimus#8]
Is there a limit we should be aware of?

**Comment by jenssegers** [comment]
I have not ran into any limitations or collisions yet in artificial tests. Probably there's some fancy math to prove it :)

**Comment by shpeilin** [comment]
Thank you.

**Comment by Wendtly** [comment]
The limit is Optimus::MAX_INT, set at 2147483647.

**Comment by jenssegers** [comment]
Just did a test for every positive integer going from 0 to Optimus::MAX_INT (2147483647) and can confirm that there are no collisions.
