### ISSUE TITLE
Separate logic of spark command

### ISSUE THREAD

**Issue by Propaganistas** [jenssegers/optimus#9]
Hi

Could you please split out the generation logic of the spark command into a separate class so that it can be called from elsewhere more easily?

I'm building a Laravel wrapper for Optimus.

Thanks.

**Comment by jenssegers** [comment]
You should be able to call the Symfony console command object from Laravel since Laravel command are Symfony commands as well. You will need to require `phpseclib/phpseclib` though. Because I build a .phar file I can place it as a dev requirement.

**Comment by Propaganistas** [comment]
Yes, but the generated numbers aren't available directly as they are immediately being consumed and then echo'ed.

It would be practical to get access the generated numbers directly?

**Comment by jenssegers** [comment]
True, but the spark is just a small helper to get started using the library quicker. I will take a look if I can find a decent structure to extract that logic. You could copy the logic of the command as well, there's no super magic stuff happening there :)

**Comment by cviebrock** [comment]
@Propaganistas did you ever publish your Laravel wrapper for this? I was looking to do the same, but if you've already done my job for me ... :wink:

**Comment by Propaganistas** [comment]
@cviebrock Yes, take a look here:

https://github.com/Propaganistas/Laravel-FakeId
